name: 'Deploy to Azure Container App'
description: 'Deploy Containers to Azure Container App. github.com/Azure/Actions'

inputs:
    resource-group:
        description: 'Name of the Resource Group in which the Container App will be created'
        required: true
    name:
        description: 'TBD: Name of the Container Group Instance - this should be aquired with cred automatically'
        required: true
    image:
        description: Name of Container Image
        required: true
    commit-hash:
        description: Commit Hash
        required: true
outputs:
    container-result:
        description: 'Sample: Container Result'
branding:
    icon: 'azure-logo.svg'
    color: 'blue'
runs:
    using: 'node16'
    main: 'lib/main.js'
