resource-group: aca-sample-rg
name: momosuke-container3
location: "East US"
subscription-id: "a4deccb1-a1f6-40cb-a923-f55a7d22c32d"
managed-environment-name: "momosuke-container-env"
dapr-app-port: 3000
dapr-app-protocol: "http"
dapr-enabled: false
ingress-external: true
ingress-target-port: 3000
ingress-custom-domains-json:
  - 
# ingress-custom-domains-json:
#   - name: www.my-name.com
#     bindingType: SniEnabled
#     certificateId: /subscriptions/a4deccb1-a1f6-40cb-a923-f55a7d22c32d/resourceGroups/aca-sample-rg/providers/Microsoft.App/managedEnvironments/momosuke-container-env/certificates/527CAD9560BF6B5F95AE62E94BF7A7CA0EC5C294ACC77622A0CF24527936C63C
# ingress-traffic-json: |
#   [
#   ]
ingress-traffic-json:
  - label: production
    revisionName: yuhattor-container3--qpxyrnn
    weight: 100
scale-max-replicas: 5
scale-min-replicas: 1
# scale-rules-json: |
#   [
#   ]
scale-rules-json:
  - name: httpscalingrule
    custom:
      type: http
      metadata:
        concurrentRequests: 30
containers-config-json:
  - name: simple-hello-world-container
    image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
    probes:
      - type: Liveness
        httpGet:
          httpHeaders:
            - name: Custom-Header
              value: Awesome
          path: /health
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
