scale-max-replicas: 5
scale-min-replicas: 1
# scale-rules-json: |
#   [
#   ]
scale-rules-json:
  - name: httpscalingrule
    custom:
      type: http
      metadata:
        concurrentRequests: "50"
