# momosuke ver.
on: [push, pull_request]
  
name: Container Deployment Sample Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install 
    - run: tsc
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Container Apps'
      uses: ./
      with:
        resource-group: aca-sample-rg
        name: momosuke-container3
        location: 'East US'
        subscription-id: 'a4deccb1-a1f6-40cb-a923-f55a7d22c32d'
        managed-environment-name: 'momosuke-container-env'
        containers-config-path: './src/containers-config.yml'
