# momosuke ver.
on: [push, pull_request]
  
name: Container Deployment Sample Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install
    - run: tsc
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Container Apps'
      uses: ./
      with:
        resource-group: aca-sample-rg
        name: momosuke-container3
        image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
        # revision-name-suffix: ${{ github.sha }}