# momosuke ver.
on: [push, pull_request]
  
name: Container Deployment Sample Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install 
    - run: tsc
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Container Apps'
      uses: ./
      with:
        resource-group: aca-sample-rg
        name: momosuke-container3
        location: 'East US'
        subscription-id: 'a4deccb1-a1f6-40cb-a923-f55a7d22c32d'
        managed-environment-name: 'momosuke-container-env'
        # dapr-app-port: 3000
        # dapr-app-protocol: 'http'
        # dapr-enabled: false
        ingress-external: true
        ingress-target-port: 3000
        # ingress-custom-domains-json: |
        #   [
        #   ]
        # ingress-custom-domains-json: |
        #   [
        #     {
        #       "name": "www.my-name.com", 
        #       "bindingType": "SniEnabled", 
        #       "certificateId": "/subscriptions/<SubscriptionId>/resourceGroups/<ResourceGroupName>/providers/Microsoft.App/managedEnvironments/<ManagedEnvironmentName>/certificates/<CertificateName>"
        #     }
        #   ]
        # ingress-traffic-json: |
        #   [
        #   ]
        # ingress-traffic-json: |
        #   [ 
        #     { 
        #       "label": "production", 
        #       "revisionName": "yuhattor-container3--qpxyrnn", 
        #       "weight": 100 
        #     } 
        #   ]
        # scale-max-replicas: 5
        # scale-min-replicas: 1
        # scale-rules-json: |
        #   [
        #   ]
        # scale-rules-json: |
        #   [
        #     {
        #       "name": "httpscalingrule",
        #       "custom": { 
        #         "type": "http", 
        #         "metadata": { 
        #           "concurrentRequests": "50" 
        #         }
        #       }
        #     }
        #   ]
        containers-config-json: | 
          [
            {
              "name":"simple-hello-world-container",
              "image": "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest",
              "probes":[
                 {
                    "type":"Liveness",
                    "httpGet":{
                       "path":"/health",
                       "httpHeaders":[
                          {
                             "name":"Custom-Header",
                             "value":"Awesome"
                          }
                       ],
                       "port":8080
                    },
                    "initialDelaySeconds":3,
                    "periodSeconds":3
                 }
              ]
            }
          ]

